export type AgentStatus = "ACTIVE" | "COMING_SOON";

export interface Agent {
  slug: string;
  name: string;
  suite: string;
  suiteName: string;
  status: AgentStatus;
  description: string;
  integrations: string[];
  companions: string[];
  cadence: string;
}

export interface Suite {
  slug: string;
  name: string;
  description: string;
  icon: string;
}

export const SUITES: Suite[] = [
  { slug: "content",       name: "Content & Publishing", description: "Create, publish, and maintain content at scale.", icon: "FileText" },
  { slug: "social",        name: "Social",               description: "Draft, schedule, and engage across every platform.", icon: "Share2" },
  { slug: "audio-video",   name: "Audio & Video",        description: "Scripts, podcasts, captions, and clips.", icon: "Mic" },
  { slug: "seo",           name: "SEO",                  description: "Technical audits, keyword research, and rank tracking.", icon: "Search" },
  { slug: "link-building", name: "Link Building",        description: "Prospecting, outreach, and placement at members-only rates.", icon: "Link" },
  { slug: "paid-media",    name: "Paid Media",           description: "Ad copy, creative, and spend optimisation.", icon: "BarChart2" },
  { slug: "lifecycle",     name: "Lifecycle & Revenue",  description: "Email, lead enrichment, reviews, and inbox.", icon: "Mail" },
  { slug: "analytics",     name: "Analytics & Reporting", description: "Weekly reports, anomaly detection, and attribution.", icon: "TrendingUp" },
  { slug: "operator",      name: "Operator",             description: "The intelligence layer that coordinates everything else.", icon: "Bot" },
];

export const AGENTS: Agent[] = [
  // ── Content & Publishing ──────────────────────────────────────────────
  {
    slug: "blog-writer",
    name: "Blog Writer",
    suite: "content",
    suiteName: "Content & Publishing",
    status: "ACTIVE",
    description: "Brief to cited, house-voice article. Researches claims before writing, runs originality and stat-uniqueness gates, and matches your brand voice via your business profile.",
    integrations: ["WordPress", "Storyblok", "Webflow"],
    companions: ["on-site-publisher", "topic-planner", "repurposer"],
    cadence: "On demand",
  },
  {
    slug: "on-site-publisher",
    name: "On-site Publisher",
    suite: "content",
    suiteName: "Content & Publishing",
    status: "ACTIVE",
    description: "Pushes approved drafts into your CMS, maps fields, uploads images to media library, and preserves schema, meta, canonicals, and internal links.",
    integrations: ["WordPress", "Storyblok", "Webflow"],
    companions: ["blog-writer"],
    cadence: "On demand",
  },
  {
    slug: "topic-planner",
    name: "Topic Planner",
    suite: "content",
    suiteName: "Content & Publishing",
    status: "COMING_SOON",
    description: "Rolling 4-week content calendar built from site inventory, competitor gaps, and near-rank opportunities. Scores gaps by winnability, not volume.",
    integrations: ["Google Search Console", "Ahrefs", "Semrush"],
    companions: ["blog-writer", "keyword-research"],
    cadence: "Monthly",
  },
  {
    slug: "content-refresh",
    name: "Content Refresh",
    suite: "content",
    suiteName: "Content & Publishing",
    status: "COMING_SOON",
    description: "Identifies decaying posts by impressions lost over a 16-month GSC window, rewrites only the deteriorated sections, and republishes on original URLs.",
    integrations: ["Google Search Console", "WordPress", "Storyblok"],
    companions: ["on-site-publisher", "gsc-analyst"],
    cadence: "Monthly",
  },
  {
    slug: "internal-linking",
    name: "Internal Linking",
    suite: "content",
    suiteName: "Content & Publishing",
    status: "COMING_SOON",
    description: "Crawls your site, maps the link graph, finds orphaned pages and thin hubs, and proposes contextual links with exact anchor text. Enforces anchor diversity.",
    integrations: ["WordPress", "Storyblok", "Webflow"],
    companions: ["on-site-publisher", "technical-audit"],
    cadence: "Monthly",
  },
  {
    slug: "repurposer",
    name: "Repurposer",
    suite: "content",
    suiteName: "Content & Publishing",
    status: "COMING_SOON",
    description: "Transforms one published post into 4 platform-native formats: X thread, carousel outline, short-form video script, and newsletter section.",
    integrations: ["LinkedIn", "X"],
    companions: ["blog-writer", "linkedin-poster", "x-poster"],
    cadence: "On demand",
  },
  {
    slug: "landing-page-copy",
    name: "Landing Page Copy",
    suite: "content",
    suiteName: "Content & Publishing",
    status: "COMING_SOON",
    description: "Interviews you about your offer, buyers, and objections, then writes complete page copy in 3 substantially different variants: pain-led, outcome-led, and proof-led.",
    integrations: [],
    companions: ["cro-experiments", "google-ads", "onboarder"],
    cadence: "On demand",
  },
  {
    slug: "newsletter",
    name: "Newsletter",
    suite: "content",
    suiteName: "Content & Publishing",
    status: "COMING_SOON",
    description: "Monthly newsletter and drip campaigns. Selects high-performing published content, writes with an editorial through-line (not a link dump), and builds drafts in your ESP.",
    integrations: ["Mailchimp", "Klaviyo"],
    companions: ["blog-writer", "email-marketing"],
    cadence: "Monthly",
  },

  // ── Social ────────────────────────────────────────────────────────────
  {
    slug: "linkedin-poster",
    name: "LinkedIn Poster",
    suite: "social",
    suiteName: "Social",
    status: "COMING_SOON",
    description: "Drafts and schedules posts to your personal profile or company page. Batch review before publishing. Rate-ceiling protection via the official API.",
    integrations: ["LinkedIn"],
    companions: ["linkedin-engager", "repurposer"],
    cadence: "Daily",
  },
  {
    slug: "linkedin-engager",
    name: "LinkedIn Engager",
    suite: "social",
    suiteName: "Social",
    status: "COMING_SOON",
    description: "Drafts contextual comments and personalised connection notes for LinkedIn conversations. One-click-send from your account — never fully automated to avoid TOS risk.",
    integrations: ["LinkedIn"],
    companions: ["linkedin-poster"],
    cadence: "Daily",
  },
  {
    slug: "x-poster",
    name: "X Poster",
    suite: "social",
    suiteName: "Social",
    status: "COMING_SOON",
    description: "Drafts standalone posts, full threads (5-6 posts, lead with conclusion), replies, and quote posts. Distributes across the week, never bulk-posts.",
    integrations: ["X"],
    companions: ["x-engager", "repurposer"],
    cadence: "Daily",
  },
  {
    slug: "x-engager",
    name: "X Engager",
    suite: "social",
    suiteName: "Social",
    status: "COMING_SOON",
    description: "Monitors defined X lists and accounts, scores posts for relevance, and drafts replies and quote posts that add substance — not noise.",
    integrations: ["X"],
    companions: ["x-poster"],
    cadence: "Continuous",
  },
  {
    slug: "meta-poster",
    name: "Meta Poster",
    suite: "social",
    suiteName: "Social",
    status: "COMING_SOON",
    description: "Manages Facebook pages and Instagram feeds, stories, and reels. Writes distinct content per surface and schedules against engagement patterns via Meta Graph API.",
    integrations: ["Meta"],
    companions: ["short-form"],
    cadence: "Daily",
  },
  {
    slug: "youtube",
    name: "YouTube",
    suite: "social",
    suiteName: "Social",
    status: "COMING_SOON",
    description: "Optimises YouTube metadata: title options, description, chapter markers, and tags. Weekly comment sweep with drafted replies.",
    integrations: ["YouTube"],
    companions: ["video-script", "captions-clips"],
    cadence: "Weekly",
  },
  {
    slug: "short-form",
    name: "Short-Form",
    suite: "social",
    suiteName: "Social",
    status: "COMING_SOON",
    description: "Hook, script, and caption for Reels, Shorts, and TikTok. Hook-first structure, shot-by-shot script with on-screen text cues, per-platform pacing adjustments.",
    integrations: [],
    companions: ["meta-poster", "youtube", "repurposer"],
    cadence: "On demand",
  },
  {
    slug: "community",
    name: "Community",
    suite: "social",
    suiteName: "Social",
    status: "COMING_SOON",
    description: "Surfaces Reddit, Quora, and forum threads with genuine relevance and drafts substantive answers without self-promotion. Manual posting from your own account only.",
    integrations: ["Reddit"],
    companions: ["social-listening"],
    cadence: "Weekly",
  },
  {
    slug: "social-listening",
    name: "Social Listening",
    suite: "social",
    suiteName: "Social",
    status: "COMING_SOON",
    description: "Monitors brand and competitor mentions across X, Reddit, public Facebook/Instagram, forums, news, and review sites. Daily digest with drafted replies.",
    integrations: ["X", "Reddit"],
    companions: ["community", "review-engine"],
    cadence: "Daily",
  },

  // ── Audio & Video ─────────────────────────────────────────────────────
  {
    slug: "podcast",
    name: "Podcast",
    suite: "audio-video",
    suiteName: "Audio & Video",
    status: "ACTIVE",
    description: "Blog or topic to script to show notes to voiced audio, hosted. TTS voicing and draft upload to Transistor with approval before publishing.",
    integrations: ["Cartesia", "Transistor"],
    companions: ["blog-writer", "video-script"],
    cadence: "On demand",
  },
  {
    slug: "video-script",
    name: "Video Script",
    suite: "audio-video",
    suiteName: "Audio & Video",
    status: "COMING_SOON",
    description: "Long-form video scripts with cold opens, B-roll markers, shot lists, and timing estimates. Teleprompter-compatible format with YouTube metadata included.",
    integrations: [],
    companions: ["youtube", "captions-clips", "short-form"],
    cadence: "On demand",
  },
  {
    slug: "captions-clips",
    name: "Captions & Clips",
    suite: "audio-video",
    suiteName: "Audio & Video",
    status: "COMING_SOON",
    description: "Transcribes long-form video or podcast with speaker labels, identifies 3-6 clips per hour at natural cut points, and burns platform-specific captions.",
    integrations: [],
    companions: ["podcast", "youtube", "short-form"],
    cadence: "On demand",
  },

  // ── SEO ───────────────────────────────────────────────────────────────
  {
    slug: "technical-audit",
    name: "Technical Audit",
    suite: "seo",
    suiteName: "SEO",
    status: "ACTIVE",
    description: "Crawls your site like a search engine, checks indexability, speed, structure, schema, internal links, and mobile rendering. Prioritises findings by traffic impact.",
    integrations: ["Google Search Console"],
    companions: ["gsc-analyst", "internal-linking", "schema"],
    cadence: "Monthly",
  },
  {
    slug: "keyword-research",
    name: "Keyword Research",
    suite: "seo",
    suiteName: "SEO",
    status: "COMING_SOON",
    description: "Seed-to-brief pipeline: expands seed terms, pulls real SERPs, clusters by intent (not string similarity), scores winnability, and produces briefs for Blog Writer.",
    integrations: ["Ahrefs", "Semrush"],
    companions: ["blog-writer", "topic-planner"],
    cadence: "On demand",
  },
  {
    slug: "rank-tracker",
    name: "Rank Tracker",
    suite: "seo",
    suiteName: "SEO",
    status: "COMING_SOON",
    description: "Daily position tracking with trend-break alerts. Learns normal movement bands before alerting. Weekly movement summary with cause analysis.",
    integrations: ["Google Search Console"],
    companions: ["gsc-analyst", "competitor-watch"],
    cadence: "Daily",
  },
  {
    slug: "gsc-analyst",
    name: "GSC Analyst",
    suite: "seo",
    suiteName: "SEO",
    status: "COMING_SOON",
    description: "Weekly written analysis of Search Console data. Striking-distance list (positions 11-20), win/loss callouts, and period-over-period comparisons with a 16-month data window.",
    integrations: ["Google Search Console"],
    companions: ["technical-audit", "rank-tracker", "weekly-report"],
    cadence: "Weekly",
  },
  {
    slug: "competitor-watch",
    name: "Competitor Watch",
    suite: "seo",
    suiteName: "SEO",
    status: "COMING_SOON",
    description: "Weekly competitor diffs: new pages, content rewrites, newly-won search terms, and link acquisitions. Tracks 3-5 competitors and suggests specific competitive responses.",
    integrations: ["Ahrefs", "Semrush"],
    companions: ["rank-tracker", "keyword-research"],
    cadence: "Weekly",
  },
  {
    slug: "schema",
    name: "Schema",
    suite: "seo",
    suiteName: "SEO",
    status: "COMING_SOON",
    description: "Generates and validates JSON-LD for every page type. Classifies templates, fills with real content, validates, and applies only after your approval.",
    integrations: ["WordPress", "Storyblok", "Webflow"],
    companions: ["technical-audit", "on-site-publisher"],
    cadence: "Monthly",
  },
  {
    slug: "local-seo-gbp",
    name: "Local SEO / GBP",
    suite: "seo",
    suiteName: "SEO",
    status: "COMING_SOON",
    description: "Weekly Google Business Profile posts, drafted review replies, Q&A management, and citation drift report for NAP consistency across directories.",
    integrations: ["Google Business Profile"],
    companions: ["review-engine"],
    cadence: "Weekly",
  },
  {
    slug: "ai-search-visibility",
    name: "AI-Search Visibility",
    suite: "seo",
    suiteName: "SEO",
    status: "COMING_SOON",
    description: "Tests whether buyer questions get your site cited by ChatGPT, Perplexity, and AI Overviews. Citation share score, competitor comparison, and llms.txt generation.",
    integrations: ["Google Search Console"],
    companions: ["blog-writer", "schema", "gsc-analyst"],
    cadence: "Weekly",
  },

  // ── Link Building ─────────────────────────────────────────────────────
  {
    slug: "prospector",
    name: "Prospector",
    suite: "link-building",
    suiteName: "Link Building",
    status: "COMING_SOON",
    description: "Finds and scores real link targets. Filters link farms, dead links, and inactive sites. Scores by real traffic and topical relevance — 20-50 prospects per run with contact info.",
    integrations: ["Ahrefs", "Semrush"],
    companions: ["outreach", "backlink-monitor"],
    cadence: "Weekly",
  },
  {
    slug: "outreach",
    name: "Outreach",
    suite: "link-building",
    suiteName: "Link Building",
    status: "COMING_SOON",
    description: "Personalised pitch sequences referencing specific prospect details. Automated follow-ups that stop on reply. Reply triage into categories with daily volume caps.",
    integrations: ["Gmail", "Microsoft 365"],
    companions: ["prospector", "digital-pr"],
    cadence: "Daily",
  },
  {
    slug: "digital-pr",
    name: "Digital PR",
    suite: "link-building",
    suiteName: "Link Building",
    status: "COMING_SOON",
    description: "Monitors journalist request services, matches to genuine expertise, and writes ready-to-send quotes. Deadline-aware queuing — not interview offers.",
    integrations: [],
    companions: ["outreach"],
    cadence: "Daily",
  },
  {
    slug: "placement",
    name: "Placement",
    suite: "link-building",
    suiteName: "Link Building",
    status: "COMING_SOON",
    description: "Vetted publisher marketplace with 1,100+ publishers at members-only rates. Brief articles, pay flat rates, receive live placement. Content drafted and submitted under publisher relationships.",
    integrations: [],
    companions: ["prospector", "blog-writer"],
    cadence: "On demand",
  },
  {
    slug: "backlink-monitor",
    name: "Backlink Monitor",
    suite: "link-building",
    suiteName: "Link Building",
    status: "COMING_SOON",
    description: "Weekly link profile tracking: new links, lost links, attribute changes. Toxic-link flagging, negative-SEO pattern monitoring, and a maintained disavow file.",
    integrations: ["Ahrefs", "Google Search Console"],
    companions: ["technical-audit"],
    cadence: "Weekly",
  },

  // ── Paid Media ────────────────────────────────────────────────────────
  {
    slug: "google-ads",
    name: "Google Ads",
    suite: "paid-media",
    suiteName: "Paid Media",
    status: "COMING_SOON",
    description: "RSA copywriting, search term analysis (keywords and negatives), and spend anomaly alerts same-day. Reads account via OAuth directly.",
    integrations: ["Google Ads", "Google Analytics 4", "Google Search Console"],
    companions: ["ad-creative", "cro-experiments", "weekly-report"],
    cadence: "Daily",
  },
  {
    slug: "meta-ads",
    name: "Meta Ads",
    suite: "paid-media",
    suiteName: "Paid Media",
    status: "COMING_SOON",
    description: "Creative variants across static, video, carousel, and story. Temperature-aware copy for cold, warm, and retargeting audiences. Fatigue alerts triggered by frequency and engagement decay.",
    integrations: ["Meta"],
    companions: ["ad-creative", "cro-experiments"],
    cadence: "Daily",
  },
  {
    slug: "linkedin-ads",
    name: "LinkedIn Ads",
    suite: "paid-media",
    suiteName: "Paid Media",
    status: "COMING_SOON",
    description: "B2B ad copy by funnel stage. Audience definitions from ICP firmographics. Monitors qualified lead cost — not just click cost.",
    integrations: ["LinkedIn"],
    companions: ["ad-creative", "lead-enrichment"],
    cadence: "Weekly",
  },
  {
    slug: "ad-creative",
    name: "Ad Creative",
    suite: "paid-media",
    suiteName: "Paid Media",
    status: "COMING_SOON",
    description: "Angle-by-format-by-audience concept matrix for static and video ads. Full copy per concept with headline, primary text, and on-image copy. Shoot priority ranking.",
    integrations: [],
    companions: ["meta-ads", "google-ads", "cro-experiments"],
    cadence: "On demand",
  },
  {
    slug: "cro-experiments",
    name: "CRO / Experiments",
    suite: "paid-media",
    suiteName: "Paid Media",
    status: "COMING_SOON",
    description: "Page teardown against real GA4 traffic. Hypothesis generation with mechanism identification. Sample size calculation with honest statistical power assessment.",
    integrations: ["Google Analytics 4"],
    companions: ["google-ads", "landing-page-copy"],
    cadence: "Monthly",
  },

  // ── Lifecycle & Revenue ───────────────────────────────────────────────
  {
    slug: "email-marketing",
    name: "Email Marketing",
    suite: "lifecycle",
    suiteName: "Lifecycle & Revenue",
    status: "COMING_SOON",
    description: "Broadcasts and drips built in your ESP with behavioural segmentation. Automation flows with branching logic drafted in ESP. Monitors and rewrites underperformers.",
    integrations: ["Mailchimp", "Klaviyo"],
    companions: ["newsletter", "inbox-responder"],
    cadence: "Weekly",
  },
  {
    slug: "lead-enrichment",
    name: "Lead Enrichment",
    suite: "lifecycle",
    suiteName: "Lifecycle & Revenue",
    status: "COMING_SOON",
    description: "Enriches inbound leads with company size, tech stack, and role. Scores fit against actual closed customers. Flags priority leads for same-hour outreach.",
    integrations: [],
    companions: ["inbox-responder", "outreach"],
    cadence: "Continuous",
  },
  {
    slug: "review-engine",
    name: "Review Engine",
    suite: "lifecycle",
    suiteName: "Lifecycle & Revenue",
    status: "COMING_SOON",
    description: "Requests reviews at peak satisfaction moments. Monitors multiple review platforms. Drafts tailored responses to all reviews — including negative ones. All responses require approval.",
    integrations: ["Google Business Profile"],
    companions: ["local-seo-gbp", "social-listening"],
    cadence: "Continuous",
  },
  {
    slug: "inbox-responder",
    name: "Inbox Responder",
    suite: "lifecycle",
    suiteName: "Lifecycle & Revenue",
    status: "COMING_SOON",
    description: "Sorts genuine marketing inquiries from pitches. Drafts contextual replies in your voice. Flags items needing direct attention. Never sends autonomously — everything stays in drafts.",
    integrations: ["Gmail", "Microsoft 365"],
    companions: ["lead-enrichment"],
    cadence: "Daily",
  },

  // ── Analytics & Reporting ─────────────────────────────────────────────
  {
    slug: "weekly-report",
    name: "Weekly Report",
    suite: "analytics",
    suiteName: "Analytics & Reporting",
    status: "COMING_SOON",
    description: "Written weekly report from GA4, Search Console, and Google Ads. Identifies the 3 most significant movements. Narrative prose with charts in support. Client-ready with white-label options.",
    integrations: ["Google Analytics 4", "Google Search Console", "Google Ads"],
    companions: ["anomaly-watch", "gsc-analyst"],
    cadence: "Weekly",
  },
  {
    slug: "anomaly-watch",
    name: "Anomaly Watch",
    suite: "analytics",
    suiteName: "Analytics & Reporting",
    status: "COMING_SOON",
    description: "Learns baseline bands per metric including seasonality. Alerts only on genuine deviations, not daily jitter. Correlates anomalies against deploys and SERP shifts.",
    integrations: ["Google Analytics 4", "Google Search Console", "Google Ads"],
    companions: ["weekly-report", "rank-tracker"],
    cadence: "Daily",
  },
  {
    slug: "attribution",
    name: "Attribution",
    suite: "analytics",
    suiteName: "Analytics & Reporting",
    status: "COMING_SOON",
    description: "Joins GA4 sessions to closed CRM revenue. Reports first-touch, last-touch, and assisted attribution simultaneously. Names blind spots like dark social and offline.",
    integrations: ["Google Analytics 4"],
    companions: ["weekly-report", "lead-enrichment"],
    cadence: "Monthly",
  },

  // ── Operator ──────────────────────────────────────────────────────────
  {
    slug: "onboarder",
    name: "Onboarder",
    suite: "operator",
    suiteName: "Operator",
    status: "COMING_SOON",
    description: "A 20-minute conversational interview capturing your business profile, ICP, voice guide, and goals. Reads your existing site to infer brand voice. Feeds all other agents.",
    integrations: [],
    companions: ["operator"],
    cadence: "Once (then periodically refreshed)",
  },
  {
    slug: "operator",
    name: "Operator",
    suite: "operator",
    suiteName: "Operator",
    status: "COMING_SOON",
    description: "Meta-agent: reads your business goals and last week's results, proposes a weekly plan (which agents run, on what, and why), dispatches only after human approval.",
    integrations: [],
    companions: ["onboarder", "weekly-report"],
    cadence: "Weekly",
  },
  {
    slug: "proposal",
    name: "Proposal",
    suite: "operator",
    suiteName: "Operator",
    status: "COMING_SOON",
    description: "Turns prospect info and call notes into a scoped, priced proposal. Researches the prospect, scopes to actual needs, prices from your rate card, and tracks opens.",
    integrations: [],
    companions: ["onboarder"],
    cadence: "On demand",
  },
];

export function getAgent(slug: string): Agent | undefined {
  return AGENTS.find((a) => a.slug === slug);
}

export function getAgentsBySuite(suite: string): Agent[] {
  return AGENTS.filter((a) => a.suite === suite);
}

export function getActiveAgents(): Agent[] {
  return AGENTS.filter((a) => a.status === "ACTIVE");
}

export function getSuite(slug: string): Suite | undefined {
  return SUITES.find((s) => s.slug === slug);
}
